.local/bin:
  type: "archive"
  url: "https://github.com/junegunn/fzf/releases/download/v0.56.0/fzf-0.56.0-linux_amd64.tar.gz"
.local/share/pyenv:
  type: "git-repo"
  url: "https://github.com/pyenv/pyenv.git"
  refreshPeriod: "168h"
.local/share/pyenv/plugins/pyenv-virtualenv:
  type: "git-repo"
  url: "https://github.com/pyenv/pyenv-virtualenv.git"
  refreshPeriod: "168h"

