[".local/share/pyenv"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv.git"
    exact = false # we may have compiled the bash extension
    refreshPeriod = "168h"
[".local/share/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv.git"
    exact = true
    refreshPeriod = "168h"
[".local/share/fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    clone.args = ["--depth", "1"]
    exact = true
    refreshPeriod = "168h"

