#!/bin/zsh

if [[ -n $TMUX ]]; then
    return
fi

export PATH="$HOME/.local/bin:$PATH"

# python tooling
export PYENV_ROOT=$HOME/.local/share/pyenv
export PATH="$PYENV_ROOT/bin:$PATH"

# rust tooling
export RUSTUP_HOME=$HOME/.local/share/rustup
export CARGO_HOME=$HOME/.local/share/cargo
[ -f $CARGO_HOME/env ] && source $CARGO_HOME/env

# go tooling
export GOENV_ROOT=$HOME/.local/share/goenv
export PATH=$GOENV_ROOT/bin:$PATH
export GOPATH=$HOME/.local/go
eval "$(goenv init -)"
export PATH=$GOROOT/bin:$PATH
export PATH=$PATH:$GOPATH/bin

# fzf
export PATH=$PATH:$HOME/.local/share/fzf/bin

